In [1]:
#Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
from scipy import stats
import os, time,json
from tqdm.notebook import tqdm_notebook
import tmdbsimple as tmdb

In [3]:
FOLDER = "Data/"
os.makedirs(FOLDER, exist_ok=True)
os.listdir(FOLDER)

['.ipynb_checkpoints',
 'final_title_akas.csv.gz',
 'final_title_basics.csv.gz',
 'final_title_ratings.csv.gz',
 'final_tmdb_data.csv.gz',
 'final_tmdb_data_2000.csv.gz',
 'final_tmdb_data_2001.csv.gz',
 'title-akas-us-only.csv',
 'title_akas.csv.gz',
 'title_basics.csv.gz',
 'title_ratings.csv.gz',
 'tmdb_api_results_2000.json',
 'tmdb_api_results_2001.json']

In [11]:
#Use glob to find final_tmdb_data csv files
q = FOLDER+"final_*csv.gz"
print(q)
file_list = sorted(glob.glob(q))
file_list

Data/final_*csv.gz

['Data\\final_title_akas.csv.gz',
 'Data\\final_title_basics.csv.gz',
 'Data\\final_title_ratings.csv.gz',
 'Data\\final_tmdb_data.csv.gz',
 'Data\\final_tmdb_data_2000.csv.gz',
 'Data\\final_tmdb_data_2001.csv.gz',
 'Data\\final_tmdb_data_2010.csv.gz',
 'Data\\final_tmdb_data_2011.csv.gz',
 'Data\\final_tmdb_data_2012.csv.gz',
 'Data\\final_tmdb_data_2013.csv.gz',
 'Data\\final_tmdb_data_2014.csv.gz',
 'Data\\final_tmdb_data_2015.csv.gz',
 'Data\\final_tmdb_data_2017.csv.gz',
 'Data\\final_tmdb_data_2018.csv.gz',
 'Data\\final_tmdb_data_2019.csv.gz',
 'Data\\final_tmdb_data_2020.csv.gz']

In [12]:
#Use list comprehension to load all files into 1 data frame
df = pd.concat([pd.read_csv(f, lineterminator = '\n') for f in file_list])
df.head()

C:\Users\jezep\AppData\Local\Temp\ipykernel_23264\328061894.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f, lineterminator = '\n') for f in file_list])

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle\r,tconst,titleType,...,status,tagline,video,vote_average,vote_count,certification\r\r,certification\r\r.1,certification\r\r.2,certification\r,imdb_id\r
0,tt0000001,6.0,Carmencita,US,NaN,imdbDisplay,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0000002,7.0,The Clown and His Dogs,US,NaN,NaN,literal English title,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tt0000005,10.0,Blacksmith Scene,US,NaN,imdbDisplay,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,tt0000005,1.0,Blacksmithing Scene,US,NaN,alternative,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,tt0000005,6.0,Blacksmith Scene #1,US,NaN,alternative,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#Remove zero id
df = df.loc[df['imdb_id'] != '0']
df.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle\r,tconst,titleType,...,status,tagline,video,vote_average,vote_count,certification\r\r,certification\r\r.1,certification\r\r.2,certification\r,imdb_id\r
0,tt0000001,6.0,Carmencita,US,NaN,imdbDisplay,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0000002,7.0,The Clown and His Dogs,US,NaN,NaN,literal English title,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tt0000005,10.0,Blacksmith Scene,US,NaN,imdbDisplay,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,tt0000005,1.0,Blacksmithing Scene,US,NaN,alternative,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,tt0000005,6.0,Blacksmith Scene #1,US,NaN,alternative,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#Reset index
df = df.reset_index(drop = True)
df.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle\r,tconst,titleType,...,status,tagline,video,vote_average,vote_count,certification\r\r,certification\r\r.1,certification\r\r.2,certification\r,imdb_id\r
0,tt0000001,6.0,Carmencita,US,NaN,imdbDisplay,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tt0000002,7.0,The Clown and His Dogs,US,NaN,NaN,literal English title,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tt0000005,10.0,Blacksmith Scene,US,NaN,imdbDisplay,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,tt0000005,1.0,Blacksmithing Scene,US,NaN,alternative,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,tt0000005,6.0,Blacksmith Scene #1,US,NaN,alternative,NaN,0\r,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:


#Read in dataframe again to make sure it worked
df = pd.read_csv(FOLDER+'combined_tmdb_data.csv.gz',lineterminator='\n')
df.head()

C:\Users\jezep\AppData\Local\Temp\ipykernel_23264\1389633827.py:2: DtypeWarning: Columns (0,2,3,4,5,6,7,8,9,10,11,16,20,22,23,25,26,28,29,30,32,33,34,35,38,39,40,44,45,46,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(FOLDER+'combined_tmdb_data.csv.gz',lineterminator='\n')

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle\r,tconst,titleType,...,status,tagline,video,vote_average,vote_count,certification\r\r,certification\r\r.1,certification\r\r.2,certification\r,imdb_id\r\r
0,tt0000001,6.0,Carmencita,US,NaN,imdbDisplay,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
1,tt0000002,7.0,The Clown and His Dogs,US,NaN,NaN,literal English title,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
2,tt0000005,10.0,Blacksmith Scene,US,NaN,imdbDisplay,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
3,tt0000005,1.0,Blacksmithing Scene,US,NaN,alternative,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r
4,tt0000005,6.0,Blacksmith Scene #1,US,NaN,alternative,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\r

In [15]:
#Save data to disk 
df.to_csv(FOLDER+'combined_tmdb_data.csv.gz', compression = 'gzip', index = False)

In [16]:
#Preview info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2068163 entries, 0 to 2068162
Data columns (total 49 columns):
 #   Column                 Dtype
---  ------                 -----
 0   titleId                object
 1   ordering               float64
 2   title                  object
 3   region                 object
 4   language               object
 5   types                  object
 6   attributes             object
       object
 8   tconst                 object
 9   titleType              object
 10  primaryTitle           object
 11  originalTitle          object
 12  isAdult                float64
 13  startYear              float64
 14  endYear                float64
 15  runtimeMinutes         float64
                object
 17  averageRating          float64
              float64
 19  Unnamed: 0             float64
 20  imdb_id                object
 21  adult                  float64
 22  backdrop_path          object
 23  belongs_to_collection  object
 24  budget                 float64
 25  genres                 object
 26  homepage               object
 27  id                     float64
 28  original_language      object
 29  original_title         object
 30  overview               object
 31  popularity             float64
 32  poster_path            object
 33  production_companies   object
 34  production_countries   object
 35  release_date           object
 36  revenue                float64
 37  runtime                float64
 38  spoken_languages       object
 39  status                 object
 40  tagline                object
 41  video                  float64
 42  vote_average           float64
 43  vote_count             float64
        object
.1      object
.2      object
         object
               float64
dtypes: float64(18), object(31)
memory usage: 773.2+ MB

In [19]:
#Drop unnecessary columns for hypothesis tests
drop_cols = ['adult', 'backdrop_path', 'belongs_to_collection', 'homepage', 
             'original_title', 'overview', 'poster_path', 'status', 'tagline', 
             'video', 'budget', 'genres', 'id', 'original_language', 
             'popularity', 'production_companies', 'production_countries', 
             'spoken_languages', 'title']
df = df.drop(columns = drop_cols)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2068163 entries, 0 to 2068162
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   titleId            object
 1   ordering           float64
 2   region             object
 3   language           object
 4   types              object
 5   attributes         object
   object
 7   tconst             object
 8   titleType          object
 9   primaryTitle       object
 10  originalTitle      object
 11  isAdult            float64
 12  startYear          float64
 13  endYear            float64
 14  runtimeMinutes     float64
            object
 16  averageRating      float64
          float64
 18  Unnamed: 0         float64
 19  imdb_id            object
 20  release_date       object
 21  revenue            float64
 22  runtime            float64
 23  vote_average       float64
 24  vote_count         float64
    object
.1  object
.2  object
     object
          object
dtypes: float64(12), object(18)
memory usage: 473.4+ MB